apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: moruha
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - kaz.yaml
profiles:
  - name: minikube
    patches:
      - op: add
        path: /deploy/kubectl/manifests/0
        value: minikube.yaml
